pkg/parser/parser_test.go

This PR will just remove some obsolete code/comments.

remove unused code/comments

---

.circleci/config.yml
README.md
gometalinter.json

This PR will add coveralls integration to add code coverage visibility to the repo.

add coverage to repo

---

pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/parser/arguments_parser.go
pkg/parser/bool_value_parser.go
pkg/parser/byteslice_parser.go
pkg/parser/directivedefinition_parser.go
pkg/parser/directives_parser.go
pkg/parser/enumvaluesdefinition_parser.go
pkg/parser/executabledefinition_parser.go
pkg/parser/field_parser.go
pkg/parser/fieldsdefinition_parser.go
pkg/parser/float_value_parser.go
pkg/parser/inputvaluedefinitions_parser.go
pkg/parser/int_value_parser.go
pkg/parser/list_value_parser.go
pkg/parser/object_value_parser.go
pkg/parser/operationdefinition_parser.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/schemadefinition_parser.go
pkg/parser/selectionset_parser.go
pkg/parser/typesystemdefinition_parser.go
pkg/parser/value_parser.go
pkg/parser/variabledefinitions_parser.go

This PR simplifies the code of the Lexer by changing it's signature of both Peek and Read to not emit errors but only keywords/tokens. Tests are updated accordingly.

Cleanup tests

---

pkg/parser/field_parser.go
pkg/parser/fragmentspread_parser.go
pkg/parser/inlinefragment_parser.go
pkg/parser/parser_test.go
pkg/parser/selectionset_parser.go

This PR will fix some regressions found in the recent push that led to an increase in allocations and a decrease in performance (up to 20%).
There were only a few little changes necessary to make the escape analyzer happy.
The outcome is also easier to read/maintain code for parsing selection sets.
Testing also became simpler.

Selectionset parsing allocs

---

pkg/middleware/context_middleware.go
pkg/middleware/context_middleware_test.go

This PR will implement the solution to #55
All inputs (strings/byte slices) will be quoted if they weren't already quoted.
This ensures both ease of use and correct handling by the lexer.
The literal provided to the lexer must be quoted so the lexer recognises a string.

55 context middleware quote input

---

pkg/proxy/http/proxy.go
pkg/proxy/http/proxy_integration_test.go
pkg/proxy/http/proxy_test.go

This commit fixes a potential included empty operation name, which can cause problems with older graphql implementations

Drop empty operation name

---

hack/middleware/asset_middleware.go
pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/middleware/context_middleware.go
pkg/middleware/context_middleware_test.go
pkg/middleware/graphql_middleware.go
pkg/middleware/invoke_middleware.go
pkg/middleware/invoker.go
pkg/middleware/validation_middleware.go
pkg/middleware/validation_middleware_test.go
pkg/parser/executabledefinition_parser.go
pkg/parser/parser.go
pkg/parser/parser_mock_test.go
pkg/parser/parser_testhelper_test.go
pkg/parser/typesystemdefinition_parser.go
pkg/parser/typesystemdefinition_parser_test.go
pkg/proxy/http/proxy.go
pkg/proxy/http/proxy_integration_test.go

This PR simplifies the development and usage of middlewares.
Previously the validation middleware wasn't able to validate schemas if they used base scalars but did not define them.
A new func "PrepareSchema" was added to the GraphqlMiddleware interface to solve this problem.
From within this func all middlewares can update/modify the schema to bring it in a state where the defaults of the middleware should work.
Regarding the validation middleware this means that the necessary scalars will be added to the schema before invoking the validation itself.
Another use case is the context middleware. It requires the addition of a directive to the schema which can be done in the "PrepareSchema" func. That way the directive is ready to use and the user doesn't have to define it himself.
This PR …

undefined types in middlewares

---

pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/lexer/runes/runes.go

Schema parsing on Windows is broken, because the carriage return (CR, "`\r`") is tokenized as `IDENT` instead of a whitespace.
So when parsing the default schema the parser throws following error:
````
starting testServer...
2019/10/26 16:12:48 external: unexpected token - got: IDENT want one of: [COLON], locations: [{Line:2 Column:5}], path: []
````
This PR should fix this issue and the parser should work now on Windows.
Tests has been added too.

fix parsing on windows

---

pkg/imports/fixtures/render_result.golden
pkg/imports/fixtures/scanner_result.golden
pkg/imports/graphql_file.go
pkg/imports/graphql_file_test.go
pkg/imports/imports.go
pkg/imports/imports_test.go
pkg/imports/testdata/cycle/a/a.graphql
pkg/imports/testdata/cycle/b/b.graphql
pkg/imports/testdata/deep/deeper/custom_types.graphql
pkg/imports/testdata/import_cycle.graphql
pkg/imports/testdata/nested/nested.graphql
pkg/imports/testdata/nested2/nested2.graphql
pkg/imports/testdata/scalars/json.graphql
pkg/imports/testdata/schema.graphql
pkg/imports/testdata/types/mutation.graphql
pkg/imports/testdata/types/query.graphql

This PR implements a file system scanner that understands a simple #import "file" syntax to combine multiple graphql files into one. The file also allows rendering the merged file into an io.Writer.
This will close #100

implement import scanner & GraphQL File renderer

---

pkg/ast/ast.go
pkg/ast/index.go
pkg/astnormalization/astnormalization_test.go
pkg/astnormalization/object_type_extending.go
pkg/astnormalization/object_type_extending_test.go
pkg/astnormalization/remove_type_extensions.go
pkg/astnormalization/remove_type_extensions_test.go

This PR will implement the ast_normalization functionality to extend object types by ObjectTypeExtensions and the extension removal function which is responsible for removing merged extensions.
Note that removeMergedTypeExtensions' test will be expanded as new types of extension merging are implemented.

ObjectType extension and extension removal

---

pkg/ast/ast.go
pkg/astnormalization/enum_type_extending.go
pkg/astnormalization/enum_type_extending_test.go
pkg/astnormalization/input_object_type_extending.go
pkg/astnormalization/input_object_type_extending_test.go
pkg/astnormalization/interface_type_extending.go
pkg/astnormalization/interface_type_extending_test.go
pkg/astnormalization/object_type_extending_test.go
pkg/astnormalization/remove_type_extensions_test.go
pkg/astnormalization/scalar_type_extending.go
pkg/astnormalization/scalar_type_extending_test.go
pkg/astnormalization/union_type_extending.go
pkg/astnormalization/union_type_extending_test.go
pkg/astparser/parser.go
pkg/astvisitor/simplevisitor.go
pkg/astvisitor/visitor.go

This PR will implement the normalization of the remaining type extensions.
It also contains a [commit](https://github.com/jensneuse/graphql-go-tools/commit/78fb9edba4ddf28f45661788f351e9f897fd99e0) which fixed some naming inconsistencies.

normalization of type extensions

---

pkg/execution/datasource_http_json.go

This fix copies all byte slices into the query plan instead of using references into the schema definition bytes for the http data source planner. This fixes a bug where templating and replacing of the original bytes caused problems for subsequent requests because the bytes got messed up.

copy planned variables

---

pkg/execution/datasource_graphql.go
pkg/execution/execution_test.go
pkg/execution/handler.go
pkg/execution/handler_test.go

Variable extraction into the context object led to unwanted quoted strings. This PR fixes the problem.

fix variable extraction from GraphQL Request

---

pkg/execution/execution.go
pkg/execution/execution_test.go

This PR will fix a bug where accessing a flat json object from a context argument didn't work because of mismatch between dot prefixed keys and non dot prefixed keys.

add a test and implementation for accessing a flat json object from a context argument

---

pkg/astvalidation/astvalidation.go
pkg/astvalidation/astvalidation_test.go

This PR adds the missing implementation for String and Float types on ValidArguments Rule in package astvalidation. ("validateIfValueSatisfiesInputFieldDefinition")
This PR will close #149

implement validateIfValueSatisfiesInputFieldDefinition for String and Float

---

pkg/playground/playground.go

This PR extracts the http.ServeMux into an interface.
This way users can make use of the playground package with their own HttpServeMux implementation.
Closes #151

extract http.ServeMux into interface

---

pkg/execution/execution.go
pkg/execution/execution_test.go

This PR moves the execution logic of resolving parent object fields before invoking the fetch. This resolves the issue that nested data sources were not able to get the correct field.
Closes #181 
Closes #182

Fix bug where nested objects with resolvers were not able to correctly access partent object fields

---

pkg/ast/ast_node.go
pkg/ast/ast_object_type_extension.go
pkg/astnormalization/implicit_extend_root_operation.go
pkg/astnormalization/subgraph_sdl_normalization.go
pkg/astnormalization/subgraph_sdl_normalization_test.go
pkg/federation/sdlmerge/sdlmerge.go
pkg/federation/sdlmerge/sdlmerge_test.go

An elaborate description can be found here https://tyktech.atlassian.net/browse/TT-2669
before running any visitors of `sdlmerge`, we run a helper that modifies ObjectTypeDefinition with fields to be ObjectTypeExtension

TT-2669 explicit extend keyword on subgraph major object type

---

pkg/ast/ast_value.go
pkg/ast/ast_value_test.go

Fixes #292.
GraphQL has two types of string literals: double-quoted strings and
triple-quoted "block" strings. Block strings can include unescaped white
space, lint terminators, quote and backslash characters. (These
characters must be escaped in double-quoted strings). See the String
Value section of the GraphQL spec[1] for details.
[1] https://spec.graphql.org/June2018/#sec-String-Value
This PR updates the Document.PrintValue function so it emits a
triple-quoted string for block strings in the AST. That way printed
block strings, which may contain unescape characters, will always be
valid. This assumes the string content was valid when the AST was
constructed (which seems like a reasonable assumption).
While working on this PR I realized the Document.ValueToJSON method also
has a bug. …

Update Document.PrintValue to print block strings using triple quotes

---

pkg/engine/plan/local_type_field_extractor_test.go

This is a preliminary PR for #293 and #294. The plan is to fix those
issues by rewriting the LocalTypeFieldExtractor.GetAllNodes method. This
PR adds tests to nail down the current behavior. While writing the tests
I noticed a few unhandled edge cases in addition to issue #293: concrete
interface types and union members aren't included in node children if
the types are only reachable from a root node via an interface or union.
It looks like these edge cases were partially addressed as part of #283.
The rewrite will address them as well. The union tests are currently
skipped because they don't pass at all. The issue #293 tests are also
skipped, for the same reason.
The PR also updates the existing tests so root and child nodes are
sorted before comparison. This is because the updated …

Add additional LocalTypeFieldExtractor tests and benchmark

---

pkg/engine/datasource/graphql_datasource/graphql_datasource.go
pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go

This PR fixes #314.
graphql-go-tools currently doesn't include `@requires` fields in entity
representations. This PR updates the GraphQL datasource planner to
include `@requires` fields when constructing representations for an
upstream operation.
The representations logic has been updated to use RequiresFields from
plan.FieldConfiguration. This field already includes the necessary
federation keys and required fields.
Due to the order the Planner visitor calls LeaveDocument, the
representations are updated each time a field is visited instead of
being set once during LeaveDocument. This is because ConfigureFetch is
called before LeaveDocument. It would be possible to move the code to
LeaveDocument if the visit order was reversed for the Leave* methods,
but that is a large change so it …

Include `@requires` fields when constructing entity representations

---

pkg/engine/datasource/graphql_datasource/graphql_datasource.go
pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
pkg/engine/datasourcetesting/datasourcetesting.go

Fixes jensneuse/graphql-go-tools#316.
When an entity query contains a field with a directive that includes a
variable, the variable isn't added to constructed upstream operation.
This PR makes it so variables used with directives are added as needed.

Fix federation directive variables

---

pkg/ast/ast.go
pkg/ast/ast_argument.go
pkg/ast/ast_directive.go
pkg/ast/ast_field.go
pkg/ast/ast_field_alias.go
pkg/ast/ast_fragment_spread.go
pkg/ast/ast_inline_fragment.go
pkg/ast/ast_object_field.go
pkg/ast/ast_selection.go
pkg/ast/ast_test.go
pkg/ast/ast_val_enum_value.go
pkg/ast/ast_val_float_value.go
pkg/ast/ast_val_int_value.go
pkg/ast/ast_val_list_value.go
pkg/ast/ast_val_object_value.go
pkg/ast/ast_val_string_value.go
pkg/ast/ast_val_variable_value.go
pkg/ast/ast_value.go

This PR implements copying of AST nodes used in query documents. Copying
will be used when normalizing operations for federation. Selection sets
will be copied when "expanding" inline fragments and inserting inline
fragments for fields with interface types. See the plan in #328 for
details.
I'm not sure everything that's being copied needs to be copied. For
example, it seems like it would be odd for someone to modify a value,
but I copy everything except byte slice references to be one the safe
side.
Copying could also be utilized when inlining fragments, if we wanted.
Right now there's a big warning on ReplaceFragmentSpread about field
aliasing (and it isn't clear to be that field de-duplication fully fixes
the aliasing).

Implement copying of query document AST nodes

---

pkg/engine/datasource/graphql_datasource/graphql_datasource.go
pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go

`resolveNestedArgumentType` wasn't returning the proper type when the
argument was an array inside an object.  There were two reasons for
this: first, the proper object field wasn't being carried through the
recursive addVariableDefinitionsRecursively() call that was made in
the "list" case, and second, nothing was looking through the
"array-of" to get the type of the underlying object.
The fix is just to get rid of that use of `resolveNestedArgumentType`
directly.  There's no need to try to figure out the type of the
variable from parsing the complex nesting; we already know the type of
the variable from the original document!  So now we just use that.

Fix `addVariableDefinitionsRecursively` to handle arrays inside objects.

---

pkg/engine/datasource/rest_datasource/rest_datasource_test.go
pkg/engine/plan/plan.go
pkg/engine/resolve/inputtemplate.go
pkg/engine/resolve/resolve_test.go
pkg/engine/resolve/variable.go
pkg/graphql/execution_engine_v2_test.go
pkg/graphqljsonschema/jsonschema.go
pkg/graphqljsonschema/jsonschema_test.go

This PR solves an issue where nested fields of inputs were not accessible anymore because it failed JSON schema validation. It also solves an issue similar to #369 for arguments, where quotes are not removed for the PlainRenderer.
*Before / did not work*:
- `{{ .arguments.parent.nested }}` => validation error
- when `nested` is a string: `{{ .arguments.parent.nested }}` => `"nested string value"`
*After change*:
- `{{ .arguments.parent.nested}}` => `nested string value`

fix validation errors on accessing nested fields of inputs / arguments

---

pkg/astvalidation/operation_rule_all_variables_used.go
pkg/astvalidation/operation_validation_test.go

Suppose we have this graphql query request with the following query variables:
```graphql
query book_sn($id: String) {
book_attic {
oreilly_books(
where: {
AND: [ # Parsed ast ast.ValueKindList since it contains query variables, instead of the usual ast.ValueKindVariable
{ python: { tag: { eq: "beginner" } } }
{ golang: { serial_number: { eq: $id } } }
{
OR: [
{
AND: [
{
python: {
date_published: { eq: "2022-07-29" }
}
}
{
python: { date_purchased: { eq: "2022-07-29" } }
}
]
}
{
AND: [
{
golang: {
date_published: { eq: "2022-08-01" }
}
}
{
golang: { date_purchased: { eq: "2022-08-01" } }
}
]
}
]
}
}
) {
jrr_tolkien_books
george_rr_martin_books
}
}
}
```
```json
{"id": "1801071039"}
```
This will be stored into an `ast.Document` which then gets parsed during validation in …

fix: return after parsing arg fields of type ast.ValueKindList

---

pkg/engine/datasource/graphql_datasource/graphql_datasource.go
pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go
pkg/engine/datasource/graphql_datasource/graphql_tws_handler_test.go
pkg/engine/datasource/graphql_datasource/graphql_ws_handler_test.go
pkg/engine/datasource/graphql_datasource/graphql_ws_proto_types.go

This PR exports the `SubscriptionClient`and also exports the protocol variables.
**Motivation**
In our case, we are creating the SubscriptionClient outside of the engine; without exporting the SubscriptionClient it is impossible to achieve it.
It also means that we added an extra check for the case, that a SubscriptionClient exists but does not have a context - because it was created outside of the engine context.

export SubscriptionClient and ws protocol variables

---

pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
pkg/graphql/config_factory_federation.go
pkg/graphql/config_factory_federation_test.go
pkg/graphql/config_factory_proxy.go
pkg/graphql/config_factory_proxy_test.go
pkg/graphql/engine_config_v2.go
pkg/graphql/engine_config_v2_test.go
pkg/graphql/subscription.go

This PR adds new subscription types to:
- config generator for proxy-only
- config generator for federation
Also fixes https://github.com/wundergraph/graphql-go-tools/issues/428.

add new subscription types to graphql package

---

pkg/graphql/engine_config_v2.go
pkg/graphql/engine_config_v2_test.go

This PR (finally) adds a method to `EngineV2Configuration` to enable single flight.

add method to enable single flight in engine v2 config (#313)

---

pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go

feat: disable graphql maximum subscription message size limit

---

pkg/engine/resolve/inputtemplate.go
pkg/engine/resolve/inputtemplate_test.go
pkg/graphql/execution_engine_v2_test.go
pkg/graphqljsonschema/jsonschema_test.go

This PR fixes an inconsistent behavior when using `null` in a variable for a required type (e.g. `String!`)
closes #519

fix validation skipping for null on scalars (#342)

---

pkg/engine/datasource/introspection_datasource/config_factory.go
pkg/engine/datasource/introspection_datasource/fixtures/schema_introspection_with_custom_root_operation_types.golden
pkg/engine/datasource/introspection_datasource/planner_test.go
pkg/engine/datasource/introspection_datasource/source_test.go

This PR fixes an introspection issue when custom root operation types are defined, e.g.
```
schema {
query: CustomQuery
mutation: CustomMutation
subscription: CustomSubscription
}
type CustomQuery {
friend: String
}
type CustomMutation {
addFriend: Boolean
}
type CustomSubscription {
lastAddedFriend: String
}
```
In those cases, the engine returns an "unable to resolve" error message.

fix introspection not working for custom root operation types (#356)

---

pkg/engine/plan/plan.go
pkg/engine/resolve/resolve.go
pkg/engine/resolve/resolve_test.go
pkg/graphql/config_factory_federation.go
pkg/graphql/engine_config_v2.go
pkg/graphql/execution_engine_v2_test.go

This PR allows users to register a map which allows to parse/validate/resolve custom types.
This should allow to pass through any custom scalar to the federated gql apis.
Related issues:
- https://github.com/wundergraph/graphql-go-tools/issues/179
- https://github.com/wundergraph/graphql-go-tools/issues/530
- https://github.com/wundergraph/graphql-go-tools/issues/457
- https://github.com/wundergraph/graphql-go-tools/issues/454

feat: custom resolve map

---

pkg/ast/ast_operation_definition.go
pkg/astnormalization/astnormalization_test.go
pkg/astvisitor/visitor.go
pkg/operationreport/externalerror.go

Now the error message says "operation type %s is not defined; did you forget to merge the base schema?"
where the placeholder is replaced by query/mutation/subscription

chore: improve error messages when base schema is not merged

---

pkg/astnormalization/astnormalization_test.go
pkg/astnormalization/input_coercion_for_list.go
pkg/astnormalization/input_coercion_for_list_test.go

This fix is for normalization of request where one of nested subfields of input type does not exist.
This can be checked by running such a query in input_coercion_for_list_test.go
```
query {
inputWithListNestedList(input: {
nested: {non_existing_field: true},
}) {
id
name
}
}
```
fixes https://github.com/wundergraph/graphql-go-tools/pull/559

fix for handling non existing field of input type in astnormalization

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource.go

Pass it via the graphql_datasource.Factory

feat: allow plugging a logger into the graphql subscription client

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_federation_test.go
v2/pkg/engine/plan/schemausageinfo.go
v2/pkg/engine/plan/schemausageinfo_test.go
v2/pkg/engine/plan/visitor.go
v2/pkg/engine/resolve/node_object.go

In order to understand certain schema changes, we need to extend `TypeFieldUsageInfo` with the named type of the requested field.  `TypeNames` is not enough to understand the usage of the enum.

feat: add named type info to field and usage info

---

v2/pkg/astprinter/astprinter.go
v2/pkg/astprinter/astprinter_test.go

A schema extension with no fields and only directives prints an invalid schema.
e.g. 
```graphql 
extend schema @foo
```
ends up printing to this
```graphql
extend schema @foo }
```
This change makes the printer only write a closing brace if their are fields in the schema extension.

fix: bug in astprinter that prints schema with erroneous extra brace

---

v2/pkg/engine/resolve/context.go
v2/pkg/engine/resolve/resolvable_test.go

If the trace info was not initialized (e.g. we want to always print it
if it's available, but it is not always available), we might get into
this scenario.

fix: crash when requesting trace info without initializing it

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_federation_test.go
v2/pkg/engine/plan/configuration_visitor.go
v2/pkg/engine/plan/datasource_filter_visitor.go
v2/pkg/engine/plan/planner.go
v2/pkg/engine/plan/planner_configuration.go

properly check multiple node suggestions for the same path, not depending on order of ds
track all added path by planner
do not recalculate suggestions if we don't have new fields

fix: shareable planning

---

v2/pkg/engine/resolve/loader.go
v2/pkg/engine/resolve/loader_hooks_test.go

fix: set subgraph errors on resolve context when error prop is disabled

---

v2/pkg/engine/datasource/pubsub_datasource/kafka_event_manager.go
v2/pkg/engine/datasource/pubsub_datasource/nats_event_manager.go

Avoid creating multiple triggers when the topics are defined in different orders in the schema.

fix(edfs): stable sort subject

---

v2/pkg/engine/resolve/inputtemplate.go
v2/pkg/engine/resolve/resolve_test.go
v2/pkg/engine/resolve/subscription_filter.go
v2/pkg/engine/resolve/subscription_filter_test.go

This PR ensures that we respect the value type when comparing the argument value with the event payload. Before this PR, we treated "1" as 1 and vice versa, as well as "true" = true.
Changes in a nutshell: When we have one segment we can extract the type. If we have more than one it will always result in a byte value comparison. In case of array values, we can always get the type and compare it with the argument type.

fix(edfs): filter only when type matches

---

pkg/engine/plan/plan.go

We found excessive memory usage when using the library on scale with huge requests. The following fix cleans the planner visitor fields so that they do not grow excessively..

fix leak in planner

---

pkg/astvalidation/operation_rule_valid_arguments.go
pkg/astvalidation/operation_rule_values.go
pkg/astvalidation/operation_validation.go
v2/pkg/astvalidation/operation_rule_valid_arguments.go
v2/pkg/astvalidation/operation_rule_values.go
v2/pkg/astvalidation/operation_validation.go

Addressing the following issues:
* resolve a panic case on `operation_rule_valid_arguments.go`
* resolve issue extracting operation name on `operation_rule_values.go`
* reorder validator order for a more logical validation
```graphql
query first {
characters(size: $size) {
collection {
id
}
}
}
```
```
runtime error: index out of range [-1]
```

fix: nil pointer on operation rule valid argument

---

pkg/ast/ast_val_string_value.go
pkg/ast/ast_value.go
pkg/ast/ast_value_test.go
pkg/ast/helpers.go
v2/pkg/ast/ast_val_string_value.go
v2/pkg/ast/ast_value.go
v2/pkg/ast/ast_value_test.go
v2/pkg/ast/helpers.go

Fixes #839 
Note, I considered using `gjson.AppendJSONString` for better performance, but it currently doesn't have an option to disable escaping of HTML characters - which I think would be undesirable here.  See https://github.com/tidwall/gjson/issues/362

fix: JSON block string encoding

---

v2/pkg/astparser/parser_test.go
v2/pkg/lexer/lexer.go

Previously, descriptions that read like: 
```
"""
whatever \
"""
type Whatever { ...
```
Wouldn't be parsed correctly. This updates the parsing, to ensure that it can robustly handle a single `\` in a variety of different contexts: `block descriptions`, `non-block descriptions`, `comments` and `default values`

feat: ensure that correctly parse backslashes

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
v2/pkg/engine/datasource/graphql_datasource/graphql_tws_handler.go
v2/pkg/engine/datasource/graphql_datasource/graphql_ws_handler.go
v2/pkg/engine/resolve/resolve.go

This PR fixes
- Remove pond worker and unnecessary mutex locks to avoid deadlock in event loop. A semaphore has been introduced to limit concurrency.
- goroutine leak in the websocket origin handlers. We did not abort `readBlocking` on context cancellation.

fix: goroutine leak and deadlock in ws event loop

---

v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go
v2/pkg/engine/datasource/graphql_datasource/graphql_tws_handler.go
v2/pkg/engine/datasource/graphql_datasource/graphql_ws_handler.go
v2/pkg/epoller/epoll_bsd.go
v2/pkg/epoller/epoll_linux.go

I was able to remove the requirement to read twice into a timeout. This allows us to poll faster, which resulted in unnecessary CPU pressure, which I fixed with a ticker. I've made the ticker dynamic so that it can "speed" up when the events queue is full. I've tested this with our benchmarks. Finally, I've tweaked the defaults to balance CPU pressure, latency and throughput for 10k subscriptions and higher. In addition, I've moved some code out of the protocol handlers to simplify the code a bit.

chore: improve epoll impl

---

v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go

This PR ensures that we always process epoll events with limited concurrency. Additionally, to avoid spinning the CPU in the event loop, we ensure that minimum `delay` is waited. This takes the processing time into consideration. Those changes produces very stable CPU times.
We should potentially expose EpollConfiguration to allow users to tweak the performance in more demanding environments.
@jensneuse I was not able to reproduce an epoll issue while handling unsubscribe events concurrently. Let me know if you have an reproduction case.

fix(epoll): limit concurrency

---

v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go

The previous implementation relied on mutexes and locking to achieve concurrency.
This resulted in a lot of complex code.
In addition, I believe that it was possible that events are being handled while we continue with the next loop as we didn't wait for their completion.
Furthermore, one shortcoming of the previous version was that we would always have some CPU spinning when there are 0 connections as we had no means to stop the loop.
This refactor replaces the shared memory + mutex approach with an event loop.
As a result, we have 0% CPU in idle.
Another benefit is that we're able to handle incoming connection events parallel to managing connections.
This is possible as we've moved all connection management to the main loop while handling connection events in the workers. Previously, …

feat: make epoll impl lock free and non CPU blocking when idle

---

v2/pkg/engine/resolve/loader.go
v2/pkg/engine/resolve/resolvable.go

This PR ensures that we use our parser pool for all parse operations. Therefore we wanted to panic in several places. I removed those places and favor explicit error handling or partial responses instead of service interruption.
The changes reduces object allocation by an big magnitude and comes with a nice memory improvements ~6% in my simplified benchmark. I do expect much bigger saving in real-life scenarios. This change can be significant for use cases with large variables input.
Inuse_objects
Alloc_space

fix: use parser pool, avoid panic during parse

---

go.work.sum
v2/go.mod

https://github.com/goccy/go-json/releases/tag/v0.10.3

chore: upgrade github.com/goccy/go-json to pick up fixes

---

v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go

We have used the unsubscription channel of the epoll implementation for both paths, although epoll can be disabled. This led to a deadlock.
Related Cosmo PR: https://github.com/wundergraph/cosmo/pull/1380

fix(ws): deadlock on unsubscribe when epoll disabled

---

v2/pkg/engine/resolve/resolve.go

Previous work for multipart added a timer for regular heartbeat messages which could be set to keep the subscription connection alive. We had configured it to always be 5 seconds, but that caused friction in our cosmo tests which wanted to verify that the heartbeat would be sent. This PR allows for it to be configurable via options, so that we can change it in our tests and save a few seconds.

feat: make multipart heartbeat configurable

---

v2/pkg/engine/datasource/httpclient/nethttpclient.go
v2/pkg/engine/resolve/loader.go

This will be added to https://github.com/wundergraph/cosmo/pull/1445, to ensure that it's more resilient
Previously, we weren't setting the request (even when we really should have had access), because in error cases we were exiting before setting the request/response context. This ensures that we can pass the correct information to the access logs

fix: set request in hook context before send request, in case of error

---

pkg/astprinter/astprinter.go
pkg/astprinter/astprinter_test.go
v2/pkg/astprinter/astprinter.go
v2/pkg/astprinter/astprinter_test.go

Just copied relevant part from EnterObjectTypeDefinition()
Also add tests
Fixes #1018

fix(astprinter): implement transitive interface output

---

v2/pkg/engine/resolve/resolve.go
v2/pkg/engine/resolve/resolve_test.go

The semaphore in the sync method was blocking requests after the 1024th from proceeding.

fix: remove semaphore from ResolveGraphQLSubscription

---

v2/pkg/engine/resolve/resolve.go
v2/pkg/engine/resolve/resolve_test.go

After the last refactor we weren't waiting anymore for the in flight requests to be delivered, so I restored the previous behavior.

fix: wait for updates in flight to be delivered before shutting down the trigger

---

execution/engine/execution_engine.go
v2/pkg/apollocompatibility/flags.go
v2/pkg/engine/resolve/resolvable.go
v2/pkg/errorcodes/const.go
v2/pkg/variablesvalidation/variablesvalidation.go
v2/pkg/variablesvalidation/variablesvalidation_test.go

- Adds a new struct to `apollocompatibility` for "router flags" which are compatibility flags for migration from apollo router instead of apollo gateway
- Adds a special path to invalid variable validation to return the router-shaped error
- Plumbs the config through engine/execution code
This has been tested with `cosmo/router-tests` E2E and functions correctly. Critique re: naming welcome, I just picked something and moved on to the fix.

feat: add apollo router compat flag for invalid variable rendering

---

execution/engine/execution_engine.go

followup to #1067, not caught in review, just an unused field

chore: remove unused apolloRouterCompatabilityFlags from execution engine

---

v2/Makefile
v2/pkg/engine/resolve/resolve.go
v2/pkg/engine/resolve/resolve_test.go

This PR fixes an issue where `WaitGroup.Wait` caused a deadlock with the progressing update events because waiting in the event loop starves it forever.
Additionally, I removed the field `done`, which caused a race with a concurrent event from the WS providers. It also wasn't useful at all.
I battle-tested the change with a load test scenario where connections are reestablished multiple times a second.

fix: deadlock when waiting on inflight events of a trigger

---

execution/engine/execution_engine_test.go

`ApolloRouterCompatibilitySubrequestHTTPError` to `true` when testing ok-ish error codes, still passes.

test: correctly enable subrequest http errors for the subrequest http error + ok error code test

---

pkg/execution/handler.go

This pull request will remove the obsolete packr generate directive so that folks will have an easier time contributing to this repository since they won't need to have packr installed locally.
This is a follow-up to #360 where it got missed.
Signed-off-by: Steve Coffman <steve@khanacademy.org>

chore: remove obsolete packr generate directive

---

README.md

I've noticed some examples from the README do not work properly. Updated the code so that it compiles and outputs expected values.
Only https://github.com/wundergraph/graphql-go-tools/commit/81fc13c27ffb10f13660e44c8fd25e1d57d5645a should be properly reviewed. The second commit makes the indentation uniform for entire code snippet.

Fix: README.md code snippet

---

v2/pkg/engine/plan/configuration.go
v2/pkg/engine/plan/datasource_filter_collect_nodes_visitor.go
v2/pkg/engine/plan/datasource_filter_visitor.go
v2/pkg/engine/plan/planner.go

This update introduces a new configuration option, MaxDataSourceCollectorsConcurrency, to control the maximum number of concurrent data source collectors. The nodesCollector and DataSourceFilter have been modified to utilize this new setting, allowing a stricter resource management during data collection.

feat: add max concurrency for data source collectors

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go
v2/pkg/engine/datasource/graphql_datasource/graphql_tws_handler.go
v2/pkg/engine/datasource/graphql_datasource/graphql_ws_handler.go
v2/pkg/engine/datasource/graphql_datasource/graphql_ws_proto_types.go
v2/pkg/engine/resolve/resolve.go

This PR adds proper Ping/Pong support for upstream subgraphs. It ensures that the subgraph doesn't mark the connection as dead. For instance, the `graphql-ws` library supports lazy close timeouts. If the router doesn't signal that it is alive, the connection will be aborted, along with all subscriptions.

fix(websocket): handle ping/pong correctly

---

v2/pkg/engine/resolve/resolve.go

We accidentally forwarded the `complete` channel from a subscription to the shared subscription updater instance. That led to short-circuit scenarios. This was also the case in `Done`, it could have resulted in subscriptions that weren't shut down properly and therefore produce go routine leaks.

fix: dont use completed channel in sub updater

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go

This PR ensures that we use `readTimeout` for all read operations. Additionally, we use a more realistic default timeout to prevent running into issues.

fix: use proper read timeout

---

v2/pkg/engine/resolve/resolve.go

Improves performance once https://github.com/wundergraph/cosmo/pull/1795 is merged, as that PR moves the intermediate buffer from engine into the router.
This is technically a behaviourally breaking change, as `writer` could be written to in `err` case, before it would not have been. Our tests all still pass, which means we weren't asserting the previous behaviour, but some consumer could theoretically depend on it as the router did.

feat: remove intermediate buffer from ResolveGraphQLResponse

---

execution/graphql/normalization_test.go
execution/graphql/schema.go
execution/graphql/schema_test.go
pkg/ast/ast_description.go
pkg/ast/ast_test.go
pkg/astprinter/astprinter.go
pkg/astprinter/astprinter_test.go
pkg/asttransform/baseschema_test.go
pkg/astvalidation/reference/testsgo/harness_test.go
pkg/engine/datasourcetesting/datasourcetesting.go
pkg/federation/schema.go
pkg/graphql/schema.go
pkg/graphql/schema_test.go
pkg/internal/unsafeprinter/unsafeprinter.go
pkg/introspection/converter_test.go
v2/doc.go
v2/pkg/ast/ast_description.go
v2/pkg/ast/ast_test.go
v2/pkg/astminify/minify.go
v2/pkg/astnormalization/astnormalization_test.go
v2/pkg/astprinter/astprinter.go
v2/pkg/astprinter/astprinter_test.go
v2/pkg/asttransform/baseschema_test.go
v2/pkg/astvalidation/reference/testsgo/harness_test.go
v2/pkg/engine/datasource/graphql_datasource/graphql_datasource.go
v2/pkg/engine/plan/node_selection_builder.go
v2/pkg/federation/schema.go
v2/pkg/internal/unsafeprinter/unsafeprinter.go
v2/pkg/introspection/converter_test.go

For v1 and v2 this fixes the default behaviour of the PrintIndent and
PrintStringIndent functions of astprinter. Instead of printing indent
twice for every depth level, it prints it once per level.
The fix does not alter output for other parts, golden tests
are intact. Tests were modified by passing correctly sized indent.
Fixes #405

fix: print indent once per level by default

---

v2/pkg/engine/datasource/graphql_datasource/configuration.go
v2/pkg/engine/datasource/graphql_datasource/graphql_datasource.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go

In the router we use negation in regex expression matching via a negation flag, since we also use this logic when creating connections, and we need to assign connections correctly, we apply this logic in the engine.
**Tests**
Add unit tests for checking the hash. There used to be tests that tests if a connection is reused, but it has been removed with certain changes. I would need more time to go through the engine to figure out how to restructure the tests (and why they were removed in the first place) https://github.com/wundergraph/graphql-go-tools/commit/3ec0ebef5a8ab6133b411ab009fe8da289701c5f#diff-2a8da55a93918e23bbe398ea85eb27a43292dd9cc3090eea26264094dc28931bL355-L365

feat: use new negation regex matching for matching connections

---

execution/graphql/result_writer.go
v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
v2/pkg/engine/datasource/graphql_datasource/graphql_sse_handler.go
v2/pkg/engine/datasource/graphql_datasource/graphql_tws_handler.go
v2/pkg/engine/datasource/graphql_datasource/graphql_ws_handler.go
v2/pkg/engine/resolve/event_loop_test.go
v2/pkg/engine/resolve/resolve.go
v2/pkg/engine/resolve/resolve_test.go
v2/pkg/engine/resolve/response.go

In #1158, I added a new path for handling server closure, but as an unintended side effect some scenarios that were previously silently failing such as complete-after-error in subscription init events became obviously broken.
This PR follows up on this by adding options for the _kind_ of closure the caller wants, including 3 to start:
- "normal" = the connection is being closed normally and intentionally, such as in the case of connection failure
- "downstream service error" = the subgraph closes the connection before completing
- "going away" = used during router shutdown to indicate the router itself is shutting down
It also:
- renames many instances of "Shutdown" to "Close" and "Done" to "Complete" for consistent terminology through the router and engine for subscriptions. 
- corrects …

fix: support different kinds of close, correct client unsubscribe behaviour

---

execution/subscription/legacy_handler_test.go
v2/pkg/apollocompatibility/flags.go
v2/pkg/astvalidation/operation_rule_fragments.go
v2/pkg/astvalidation/operation_rule_validate_field_selections.go
v2/pkg/astvalidation/operation_validation.go
v2/pkg/astvalidation/operation_validation_test.go
v2/pkg/astvalidation/reference/testsgo/ScalarLeafsRule_test.go
v2/pkg/astvalidation/reference/testsgo/harness_test.go
v2/pkg/astvisitor/visitor.go
v2/pkg/engine/resolve/resolvable.go
v2/pkg/operationreport/externalerror.go

Currently, we only have Apollo Gateway compatibility for a few basic types of field selection validation, this PR expands it to include and test:
- selecting an undefined operation
- selecting on an enum
- selecting on a scalar
- no select on object
- select non-existent field
- invalid fragment spread
The Apollo extension and 400 status compatibility should also extend to all operation validation errors now, and as such is governed by a new, less specific flag.
It also changes the format for a few existing errors:
| Old Format                                                  | New Format                                                                                  |
| ----------------------------------------------------------- | …

feat: improve apollo gateway compatible field selection validation

---

v2/pkg/engine/resolve/fetchtree.go

This currently panics because https://github.com/wundergraph/graphql-go-tools/blob/e75a1dd24d5255b6cc990269c5c7922f851f4fc1/v2/pkg/engine/resolve/fetchtree.go#L212-L213 is a nil pointer dereference when 
This change makes it just fail empty instead of panic, which is fine for what it's needed for in the router.
I originally made this not nil at the source in https://github.com/wundergraph/graphql-go-tools/blob/dd0d9cc2a9192799c4b3c5ecaa89134c03e01801/v2/pkg/engine/plan/visitor.go#L1259-L1261
but it causes like 1000+ inline snapshot tests to fail which are hardcoded and don't have `-update`, so I catch the nilness at usage site instead

fix: don't panic when calling QueryPlan on FetchTreeNode if `includeQueryPlans` is false

---

v2/pkg/astminify/minify_test.go

Use existing files for the simple benchmark instead of dev's temporaries.
Remove tests under WG_INTERNAL os env var.
@coderabbitai summary

fix: use existing files in BenchmarkMinify
