wundergraph/graphql-go-tools

pkg/lexer/fixtures/introspection_lexed.golden
pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/lexing/position/position.go.go

This PR adds EndLine+EndChar Positions to every emitted token by the lexer.
In an additional PR the AST produced by the parser will be enhanced with end positions.

Add start end position to nodes

---

pkg/lexer/fixtures/introspection_lexed.golden
pkg/lexer/lexer.go
pkg/lexing/position/position.go
pkg/lexing/token/token.go
pkg/lookup/iterable.go
pkg/lookup/lookup.go
pkg/lookup/walker.go
pkg/lookup/walker_enum.go
pkg/parser/directivedefinition_parser.go
pkg/parser/enumtypedefinition_parser.go
pkg/parser/inputobjecttypedefinition_parser.go
pkg/parser/interfacetypedefinition_parser.go
pkg/parser/objecttypedefinition_parser.go
pkg/parser/scalartypedefinition_parser.go
pkg/printer/fixtures/introspection.golden
pkg/printer/fixtures/printer_introspection.golden
pkg/printer/fixtures/starwars_typesystem.golden
pkg/printer/printer.go
pkg/printer/printer_test.go

This PR will add basic Type System Definition printing to the ast printer.

Add typesystem printer

---

pkg/validator/validator_test.go

This PR will fix a misleading benchmark result.

fix misleading benchmark results

---

pkg/parser/enumvaluesdefinition_parser.go
pkg/parser/fieldsdefinition_parser.go
pkg/parser/inputvaluedefinitions_parser.go
pkg/parser/typesystemdefinition_parser.go
pkg/parser/typesystemdefinition_parser_test.go

This PR will make the parser accept comments prefixed with a hashtag.

Parser accept comments

---

pkg/proxy/config.go
pkg/proxy/http/proxy.go
pkg/proxy/http/proxy_integration_test.go

For application on requests to the backend servers

Add headers to request config

---

README.md
pkg/proxy/http/proxy.go
pkg/proxy/http/proxy_test.go

Handle DispatchRequest error in a non-silent way

---

pkg/middleware/invoker.go
pkg/proxy/http/proxy.go
pkg/proxy/http/proxy_test.go
pkg/proxy/proxy.go

Pass variables along with outgoing request to backend graphql server

---

pkg/middleware/context_middleware_test.go
pkg/middleware/invoker.go
pkg/parser/list_value_parser.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/value_parser.go
pkg/proxy/http/proxy.go
pkg/proxy/proxy.go

Also ran `make format`, so there might be other things in the PR

Failing empty list bug

---

go.mod
go.sum
pkg/execution/execution.go
pkg/execution/execution_test.go
pkg/lexer/literal/literal.go

This PR will fix issues when using complex nested structures for input variables.

add implementation and tests for complex nested input variable rendering

---

pkg/execution/execution.go
pkg/execution/handler.go
pkg/execution/handler_test.go

This PR will ensure that extra arguments get added to the execution context as context arguments so that they are available during execution.

add extra arguments to execution context

---

pkg/execution/datasource_graphql.go
pkg/execution/execution_test.go

This is a small fix to fix String variable encoding.

add test and implement fix for variable enconding using Strings only for now

---

pkg/execution/execution.go
pkg/execution/execution_test.go
pkg/lexer/literal/literal.go

This PR implements object variable templating.
Closes #142

add test and implement object variable templating

---

go.mod
go.sum
pkg/execution/datasource_graphql.go
pkg/execution/execution.go
pkg/execution/execution_test.go
pkg/execution/handler.go
pkg/execution/handler_test.go
pkg/execution/transformation_test.go
pkg/lexer/literal/literal.go

This PR will give the library user the possibility to supply custom directives for argument resolution to the execution.Handler.
This closes #156

implement arg templating with custom directives

---

pkg/engine/resolve/resolve.go
pkg/engine/resolve/resolve_test.go

fix resolving error for nested non-nullable object

---

pkg/engine/resolve/resolve.go
pkg/engine/resolve/resolve_test.go

Fix an issue #298 .
`jsonparser.Get` [strips](https://github.com/buger/jsonparser/blob/master/parser.go#L974) quotes from string value, in case if `jsonparser.Get` is called outside of `resolveString` method, there is no way to distinguish if value is stringified number ("123") or number (123).

fix resolving array of strings with stringified number

---

pkg/astvalidation/operation_rule_valid_arguments.go
pkg/astvalidation/operation_validation_test.go

This PR fixes #318.
Per the GraphQL spec[1], non-null variable types are compatible with
nullable types, even when such types are list items. This PR adjusts the
varialbe validation algorithm so non-null types are allowed to match
nullable types when they appear in lists (to arbitrary depth).
[1] https://spec.graphql.org/June2018/#AreTypesCompatible()

Fix validation of non-null types in list arguments

---

pkg/astvalidation/rule_unique_field_definition_names.go
pkg/astvalidation/rule_unique_field_definition_names_test.go

First attempt to add changes upstream

Unique field input typo fix

---

pkg/engine/plan/plan.go

regression from https://github.com/wundergraph/graphql-go-tools/pull/373
fixes ENG-907

fix planning variable path

---

pkg/astparser/parser.go
pkg/astparser/parser_test.go

Fix: Cannot specify extend after blockstring

---

pkg/engine/datasource/graphql_datasource/batch.go

This fix improves drastically performance of enriching data in federated services. The inner for loop in jsonparser.ArrayEach is bottleneck if response to be enriched is large and has unique keys. 
The reason is size of responseMapping will grow to size of input, making computation n^2.
In our case the fix reduced time from 20minutes to 16 seconds for response with hundred thousand objects.

improve performance of batch fetching

---

v2/pkg/engine/datasource/graphql_datasource/graphql_sse_handler.go

content-type must be application/json

fix: set appropriate headers for SSE requests via POST

---

v2/pkg/engine/resolve/loader.go
v2/pkg/graphql/execution_engine_v2_test.go
v2/pkg/graphqljsonschema/jsonschema.go
v2/pkg/graphqljsonschema/jsonschema_test.go

provide more meaningful message when fetch input failed to render

fix json schema generation

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_federation_test.go
v2/pkg/engine/plan/abstract_selection_rewriter_helpers.go
v2/pkg/engine/plan/datasource_configuration.go
v2/pkg/engine/plan/datasource_filter_visitor.go
v2/pkg/engine/plan/federation_metadata.go

add support of key resolvable: false

---

README.md
v2/README.md

chore: update readme

---

examples/federation/gateway/gateway.go
execution/engine/execution_engine.go
execution/engine/execution_engine_test.go
execution/federationtesting/gateway/gateway.go
execution/subscription/legacy_handler_test.go
execution/subscription/websocket/handler_test.go
v2/pkg/engine/plan/visitor.go
v2/pkg/engine/resolve/node_custom.go
v2/pkg/engine/resolve/resolvable.go
v2/pkg/engine/resolve/resolve_test.go

pass resolve context to custom resolvers
expose resolve options for execution

enable custom resolve

---

v2/pkg/engine/datasource/graphql_datasource/representation_variable.go
v2/pkg/engine/datasource/graphql_datasource/representation_variable_test.go

fix: properly merge representations on the same type but with different nested selections

---

v2/pkg/astminify/fixtures/operation10.min.graphql.golden
v2/pkg/astminify/fixtures/operation10.min.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation10.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation5.min.graphql.golden
v2/pkg/astminify/fixtures/operation6.min.graphql.golden
v2/pkg/astminify/fixtures/operation6.min.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation6.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation7.min.graphql.golden
v2/pkg/astminify/fixtures/operation7.min.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation7.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation8.min.graphql.golden
v2/pkg/astminify/fixtures/operation8.min.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation8.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation9.min.graphql.golden
v2/pkg/astminify/fixtures/operation9.min.normalized.graphql.golden
v2/pkg/astminify/fixtures/operation9.normalized.graphql.golden
v2/pkg/astminify/minify.go
v2/pkg/astminify/minify_test.go
v2/pkg/astminify/operation10.graphql
v2/pkg/astminify/operation6.graphql
v2/pkg/astminify/operation7.graphql
v2/pkg/astminify/operation8.graphql
v2/pkg/astminify/operation9.graphql
v2/pkg/astminify/simpleschema.graphql

When sorting args and directives on fields, and directives on inline fragments, we're able to inline more.

feat: sort arguments and directives on fields, directives on inline fragments

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
v2/pkg/engine/plan/configuration_visitor.go
v2/pkg/engine/plan/planner.go

fix: planning of consecutive fragments and fragments on union
fix: properly populate missing paths after each configuration walk

fix: planning of consecutive fragments and fragments on union

---

v2/pkg/engine/resolve/resolvable.go
v2/pkg/engine/resolve/resolvable_test.go

feat: add non-nullable field errors to value completion extension for compatibility mode

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_federation_test.go
v2/pkg/engine/plan/datasource_filter_collect_nodes_visitor.go
v2/pkg/engine/plan/datasource_filter_node_suggestions.go
v2/pkg/engine/plan/datasource_filter_visitor.go
v2/pkg/engine/plan/provides_fields_visitor.go
v2/pkg/engine/plan/provides_fields_visitor_test.go

fix: provides edge cases

---

v2/pkg/engine/datasource/graphql_datasource/graphql_datasource.go
v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_federation_test.go
v2/pkg/engine/plan/configuration_visitor.go
v2/pkg/engine/plan/datasource_filter_collect_nodes_visitor.go
v2/pkg/engine/plan/datasource_filter_node_suggestions.go
v2/pkg/engine/plan/node_selection_visitor.go

- do not add representation for root level request
- cleanup configuration visitor

fix: requires+provides edge case

---

v2/pkg/engine/resolve/resolve.go

We already limit the number of concurrent subscription updates through a semaphore. Removing the race around tools removes a deadlock when many subscriptions 7K+ are trying to close and update. This also impacted regular http requests since the getTools was shared. I tested the update with 10K subscriptions and couldn't find any impact on memory usage.

fix(subscriptions): avoid deadlock on race for tools

---

execution/engine/execution_engine.go
v2/pkg/apollocompatibility/flags.go
v2/pkg/astvalidation/operation_rule_validate_field_selections.go
v2/pkg/astvalidation/operation_validation.go
v2/pkg/astvalidation/operation_validation_test.go
v2/pkg/variablesvalidation/variablesvalidation.go
v2/pkg/variablesvalidation/variablesvalidation_test.go

to produce errors with extension codes

chore: evaluate apollo compatibility replace invalid var flag 

---

v2/pkg/ast/ast.go
v2/pkg/astparser/parser.go
v2/pkg/astparser/tokenizer.go
v2/pkg/astvisitor/visitor.go
v2/pkg/engine/datasource/graphql_datasource/entity_interfaces_engine_config.go
v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_federation_entity_interfaces_test.go
v2/pkg/engine/datasource/graphql_datasource/representation_variable.go
v2/pkg/engine/plan/datasource_filter_collect_nodes_visitor.go
v2/pkg/engine/plan/datasource_filter_visitor.go
v2/pkg/engine/plan/required_fields_visitor.go
v2/pkg/engine/plan/visitor.go
v2/pkg/engine/resolve/loader.go
v2/pkg/engine/resolve/resolve.go
v2/pkg/engine/resolve/variables_renderer.go

Remove some usages of pools where it wasn't useful but only increase inuse memory.
Introduce pools in other areas where benchmarks were able to show improvements.
Reduce default size of some objects.

chore: improve memory usage of planning & execution

---

v2/pkg/variablesvalidation/variablesvalidation.go
v2/pkg/variablesvalidation/variablesvalidation_test.go

#1067 followup, fix some misspellings

fix: use correct compatibility spelling

---

v2/pkg/engine/postprocess/postprocess.go

If a query contains multiple variables, we were not able to fully parse the input because it contained engine placeholder. This PR tries to get the query without expecting a full valid JSON object. I stumbled across this because I saw many error logs.

fix: get query for plan when input is not valid JSON yet

---

v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go

This PR ensures that we use a proper frame timeout. Before we used the `readTimeout` as frame timeout which is usually 50x higher than a recommended value for the frames. This has result in conflicts with other timeouts.
I tested this with a demo setup for 2h where a subgraph writes events every 2minutes.

feat(subscriptions): user proper frame timeout

---

v2/pkg/engine/resolve/context.go
v2/pkg/engine/resolve/resolvable.go
v2/pkg/engine/resolve/resolvable_custom_field_renderer_test.go

Add the parsed AST node of the JSON along with the raw bytes.
Add isEnum flag to detect if a string value is an enum.

feat: expose parsed data in RenderFieldValue
